name: "mongo-sharding-repl"

services:
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1r1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1r1
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard1r1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1r2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1r2
    restart: always
    ports:
      - "27022:27022"
    volumes:
      - shard1r2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1r3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1r3
    restart: always
    ports:
      - "27023:27023"
    volumes:
      - shard1r3-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2r1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2r1
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2r1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs1",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  shard2r2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2r2
    restart: always
    ports:
      - "27024:27024"
    volumes:
      - shard2r2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs1",
        "--bind_ip_all",
        "--port",
        "27024"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2r3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2r3
    restart: always
    ports:
      - "27025:27025"
    volumes:
      - shard2r3-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs1",
        "--bind_ip_all",
        "--port",
        "27025"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  config-data:
  shard1r1-data:
  shard1r2-data:
  shard1r3-data:
  shard2r1-data:
  shard2r2-data:
  shard2r3-data:
